name = "mojiokoshi-kun"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "transcribe-db"
database_id = "831aaf36-4277-41a9-88e1-8fb0ae10f3a8"

[[r2_buckets]]
binding = "AUDIO"
bucket_name = "transcribe-audio"

[vars]
TRANSCRIBE_MODEL = "gpt-4o-mini-transcribe"
